coverage:
  range: 20..90     # First number represents red, and second represents green
                    # (default is 70..100)
  round: down       # up, down, or nearest
  precision: 2      # Number of decimal places, between 0 and 5
  
  
flags:
  petclinic-config-server:
    paths:
      - petclinic-servers/petclinic-config-server/src
  petclinic-discovery-server:
    paths:
      - petclinic-servers/petclinic-discovery-server/src