spring:
  datasource:
    url: jdbc:h2:mem:pet_clinic;mode=mysql
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: validate

  cloud:
    loadbalancer:
      ribbon:
        enabled: false

        
logging:
  level:
    root: WARN
