spring:
  datasource:
    url: jdbc:h2:mem:pet_clinic;mode=mysql
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: validate

logging:
  level:
    root: WARN
