spring:
  datasource:
    url: jdbc:h2:mem:pet_clinic
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update


logging:
  level:
    org.springframework: INFO
